### ISSUE TITLE
DDD My Friends Are My Power script searching issue

### ISSUE THREAD

**Issue by RegularPat** [WaterKH/WayfinderProjectAPI#15]
For whatever reason, the DDD scene "My Friends Are My Power!" never returns results when searching for dialogue (someone tried searching "nuts" or "half Xehanort" and got nothing)

Could it possibly have anything to do with how there are other scenes with the same name minus the exclamation point? (in KH1 and re:coded)

**Comment by WaterKH** [comment]
This is due to updating the Script SQL table without updating the Scene SQL table as well. Most of the script updates were paired with correct scene, just missing dialogue. In the case where no dialogue was associated, the scriptId was set to 1. I just need to go back through and update the tables to alleviate this problem.
