### ISSUE TITLE
Add Pat's Notes to Scenes Table?

### ISSUE THREAD

**Issue by WaterKH** [WaterKH/WayfinderProjectAPI#71]
Not sure if there is enough room, but adding the Notes to the row would be a nice feature I think, like how it is in the Jiminy's Journal update. Concern would be row length at that point. Having it as a hover-popup may be nice, but a little unnecessary maybe.

**Comment by Capt-Blitz** [comment]
If I could make a suggestion?
Maybe having a tab just for Notes, since they can be so malleable on a scene by scene bias.
For instance, maybe this scene could have a notes page with "Strelitza dies", "Ven is controlled by Darkness"
![image](https://user-images.githubusercontent.com/116446650/206866260-dbafe115-cbef-4cba-8a39-42f98717918a.png)

**Comment by WaterKH** [comment]
Removing since not really needed.
